[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "opencv-contrib-python-headless>=4.12.0.88",
    "pyzbar>=0.1.9",
    "scikit-image>=0.25.2",
]
